#!/usr/bin/env python3
"""
setup_hook.py
-------------
git pre-commit hook을 설치합니다.
커밋할 때마다 update_readme.py가 자동으로 실행됩니다.

사용법:
    python setup_hook.py          # hook 설치
    python setup_hook.py --remove # hook 제거
"""

import os
import stat
import argparse
from pathlib import Path

HOOK_PATH = Path(".git/hooks/pre-commit")

HOOK_CONTENT = """\
#!/bin/sh
# auto-generated by setup_hook.py

# update_readme.py 실행
python update_readme.py

# 갱신된 README.md를 커밋에 포함
git add README.md
"""


def install():
    if not Path(".git").exists():
        print("❌ .git 폴더가 없습니다. toyproject 루트에서 실행해 주세요.")
        return

    if HOOK_PATH.exists():
        print("⚠️  이미 pre-commit hook이 있습니다. 덮어쓸까요? (y/N) ", end="")
        if input().strip().lower() != "y":
            print("취소했습니다.")
            return

    HOOK_PATH.write_text(HOOK_CONTENT, encoding="utf-8")

    # 실행 권한 부여
    current = stat.S_IMODE(HOOK_PATH.stat().st_mode)
    HOOK_PATH.chmod(current | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)

    print("✅ pre-commit hook 설치 완료!")
    print("   이제 git commit 할 때마다 README.md가 자동으로 갱신됩니다.")


def remove():
    if HOOK_PATH.exists():
        HOOK_PATH.unlink()
        print("✅ pre-commit hook 제거 완료.")
    else:
        print("⚠️  설치된 hook이 없습니다.")


def main():
    parser = argparse.ArgumentParser(description="git pre-commit hook 관리")
    parser.add_argument("--remove", action="store_true", help="hook 제거")
    args = parser.parse_args()

    if args.remove:
        remove()
    else:
        install()


if __name__ == "__main__":
    main()
