# Generated by Django 6.0.6 on 2026-06-23 01:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIWritingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('idea', '아이디어 발상'), ('plot', '플롯 제안'), ('correction', '문장 교정'), ('analysis', '리뷰 감상 분석')], max_length=20)),
                ('input_text', models.TextField()),
                ('output_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'AI_WRITING_LOG',
                'ordering': ['-created_at'],
            },
        ),
    ]
