# Generated by Django 6.0.6 on 2026-06-24 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WritingDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('draft_type', models.CharField(choices=[('idea', '아이디어'), ('plot', '플롯'), ('correction', '교정')], max_length=20)),
                ('genre', models.CharField(blank=True, max_length=50)),
                ('keywords', models.CharField(blank=True, max_length=200)),
                ('content', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'AI_WRITING_DRAFT',
                'ordering': ['-created_at'],
            },
        ),
    ]
