# Generated by Django 6.0.6 on 2026-06-25 01:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_writingdraft'),
        ('books', '0004_collection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyBookRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_date', models.DateField()),
                ('scores', models.JSONField(default=dict)),
                ('candidate_sources', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_recommendations', to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_book_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'DAILY_BOOK_RECOMMENDATION',
                'constraints': [models.UniqueConstraint(fields=('user', 'recommendation_date'), name='unique_user_daily_book_recommendation')],
            },
        ),
    ]
